
[numpy官方英文教程](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

## numpy属性

```
array = np.array([[1,2,3],[2,3,4]])  #列表转化为矩阵
print('number of dim:',array.ndim)  # 维度
# number of dim: 2
print('shape :',array.shape)    # 行数和列数
# shape : (2, 3)
print('size:',array.size)   # 元素个数
# size: 6
a = np.array([2,23,4],dtype=np.int) #dtype 包括 np.int  np.int32 np.float np.float32
```

## 常用创建数组方式

```
np.zeros((3,4))
np.ones((3,4),dtype = np.int)   # 数据为1，3行4列
np.empty((3,4)) # 数据为empty，3行4列,每个值都是接近于零的数
np.arange(10,20,2) # 创建连续数组,10-19 的数据，2步长
np.arange(12).reshape((3,4))    # 3行4列，0到11
np.linspace(1,10,20)    # 创建线段型数据,开始端1，结束端10，且分割成20个数据，生成线段
```

## 常用数学运算
```
np.sum()
np.min()
np.max()
np.argmin()  #索引对应元素
np.argmax()
np.mean()
np.median()
np.cumsum() #生成的每一项矩阵元素均是从原矩阵首项累加到对应项的元素之和
np.diff()
np.nonzero()  #将所有非零元素的行与列坐标分割开，重构成两个分别关于行和列的矩阵

```

> 需要对行或者列进行查找运算，就需要在上述代码中为 axis 进行赋值。 当axis的值为0的时候，将会以列作为查找单元， 当axis的值为1的时候，将会以行作为查找单元
`np.sum(a,axis=1)`



## 矩阵运算操作
- 点乘
`np.dot(a,b)` 或 `c = a.dot(b)`

- 转置
`np.transpose(c)`  或 `a.T()`



 
 ## 索引
 ```
 A = np.arange(3,15).reshape((3,4))
"""
array([[ 3,  4,  5,  6]
       [ 7,  8,  9, 10]
       [11, 12, 13, 14]])
"""
         
print(A[2])         
# [11 12 13 14]

print(A[1][1])      # 8
print(A[1, 1])      # 8
print(A[1, 1:3])    # [8 9]

for row in A:
    print(row)
"""    
[ 3,  4,  5, 6]
[ 7,  8,  9, 10]
[11, 12, 13, 14]
"""
```

## 数组的转化
- 合并

`np.vstack((A,B)`与`np.hstack((A,B))`分别是按照上下，左右合并
```
print(np.vstack((A,B)))    # vertical stack
"""
[[1,1,1]
 [2,2,2]]
"""
D = np.hstack((A,B))       # horizontal stack
print(D)
# [1,1,1,2,2,2]
```

- 借助其他的函数操作进行转置 np.newaxis

```
print(A[np.newaxis,:])
# [[1 1 1]]

print(A[np.newaxis,:].shape)
# (1,3)

print(A[:,np.newaxis])
"""
[[1]
[1]
[1]]
"""

print(A[:,np.newaxis].shape)
# (3,1)

#则
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
         
C = np.vstack((A,B))   # vertical stack
D = np.hstack((A,B))   # horizontal stack

print(D)
"""
[[1 2]
[1 2]
[1 2]]
"""

print(A.shape,D.shape)
# (3,1) (3,2)
```

- 合并多个矩阵或序列 np.concatenate

```
C = np.concatenate((A,B,B,A),axis=0)

print(C)
"""
array([[1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1]])
"""

D = np.concatenate((A,B,B,A),axis=1)

print(D)
"""
array([[1, 2, 2, 1],
       [1, 2, 2, 1],
       [1, 2, 2, 1]])
"""
```

- 分割

1. 等量分割

```
print(np.split(A, 2, axis=1))
"""
[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]
"""
print(np.split(A, 3, axis=0))

# [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
```

2.不等分割 np.array_split()

```
print(np.array_split(A, 3, axis=1))
"""
[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]
"""
```

3. 其他分割 `np.vsplit()与横np.hsplit()`

```
print(np.vsplit(A, 3)) #等于 print(np.split(A, 3, axis=0))

# [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


print(np.hsplit(A, 2)) #等于 print(np.split(A, 2, axis=1))
"""
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]
"""
```

## 常用对矩阵操作方法

- clip

> 函数的格式是clip(Array,Array_min,Array_max)，顾名思义，Array指的是将要被执行用的矩阵，而后面的最小值最大值则用于让函数判断矩阵中元素是否有比最小值小的或者比最大值大的元素，并将这些指定的元素转换为最小值或者最大值。

```
print(A)
 array([[14,13,12,11]
        [10, 9, 8, 7]
        [ 6, 5, 4, 3]])

print(np.clip(A,5,9))    
 array([[ 9, 9, 9, 9]
        [ 9, 9, 8, 7]
       [ 6, 5, 5, 5]])
 ```
 
- flatten

> 这一脚本中的flatten是一个展开性质的函数，将多维的矩阵进行展开成1行的数列。而flat是一个迭代器，本身是一个object属性.

```
print(A.flatten())   
# array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

for item in A.flat:
    print(item)
    
# 3
# 4
……
# 14
```


##  One more thing

- copy

> `= `的赋值方式会带有关联性;  `np.copy()` 的赋值方式没有关联性
